// <auto-generated />
using System;
using DiveSyncBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveSyncBackend.Migrations
{
    [DbContext(typeof(DiveSyncDbContext))]
    [Migration("20260508140000_AddSacFields")]
    partial class AddSacFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveSyncBackend.Models.DiveSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AvgDepth")
                        .HasColumnType("float");

                    b.Property<double?>("AvgHeartRate")
                        .HasColumnType("float");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<double?>("EndPressure")
                        .HasColumnType("float");

                    b.Property<double?>("EntryLat")
                        .HasColumnType("float");

                    b.Property<double?>("EntryLng")
                        .HasColumnType("float");

                    b.Property<double?>("ExitLat")
                        .HasColumnType("float");

                    b.Property<double?>("ExitLng")
                        .HasColumnType("float");

                    b.Property<double>("MaxDepth")
                        .HasColumnType("float");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("float");

                    b.Property<string>("Mood")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("StartPressure")
                        .HasColumnType("float");

                    b.Property<double?>("TankVolume")
                        .HasColumnType("float");

                    b.Property<double>("Temp")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Date", "MaxDepth", "Duration", "Temp")
                        .HasDatabaseName("IX_Dives_DuplicateCheck");

                    b.ToTable("Dives");
                });

            modelBuilder.Entity("DiveSyncBackend.Models.TelemetryPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<int>("DiveId")
                        .HasColumnType("int");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("float");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DiveId");

                    b.ToTable("TelemetryPoints");
                });

            modelBuilder.Entity("DiveSyncBackend.Models.TelemetryPoint", b =>
                {
                    b.HasOne("DiveSyncBackend.Models.DiveSummary", "Dive")
                        .WithMany("TelemetryPoints")
                        .HasForeignKey("DiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dive");
                });

            modelBuilder.Entity("DiveSyncBackend.Models.DiveSummary", b =>
                {
                    b.Navigation("TelemetryPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
